/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package gurvy

import (
	"crypto/sha256"
	"encoding/hex"
	"math/big"
	"testing"

	bls12381 "github.com/consensys/gnark-crypto/ecc/bls12-381"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/fp"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/hash_to_curve"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ---------------------------------------------------------------------------
// TestCompatIsQuadraticResidue
// Property test: IsQuadraticResidue agrees with gnark-crypto fp.Sqrt.
// A value x is a residue iff Sqrt(x)² == x (and Sqrt is non-zero).
// Additionally, x² is always a residue.
// ---------------------------------------------------------------------------

func TestCompatIsQuadraticResidue(t *testing.T) {
	for i := range 1000 {
		var x fp.Element
		_, err := x.SetRandom()
		require.NoError(t, err)

		// x² is always a quadratic residue
		var x2 fp.Element
		x2.Square(&x)
		assert.Equal(t, uint64(1), IsQuadraticResidue(&x2), "x² must always be a residue")

		// For a random x, compare our result with gnark's Sqrt
		var s fp.Element
		s.Sqrt(&x)
		var s2 fp.Element
		s2.Square(&s)
		gnarkResidue := s2.Equal(&x) // gnark sqrt: s²==x iff x is a residue (or zero)
		if !x.IsZero() {
			gurvyResidue := IsQuadraticResidue(&x)
			if gnarkResidue {
				assert.Equal(t, uint64(1), gurvyResidue, "gnark says residue; gurvy must agree (i=%d)", i)
			} else {
				assert.Equal(t, uint64(0), gurvyResidue, "gnark says non-residue; gurvy must agree (i=%d)", i)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// TestCompatSqrt
// Property test: Sqrt(x²)² == x²  (result is correct square root).
// ---------------------------------------------------------------------------

func TestCompatSqrt(t *testing.T) {
	for i := range 1000 {
		var x fp.Element
		_, err := x.SetRandom()
		require.NoError(t, err)

		var x2 fp.Element
		x2.Square(&x)

		var gSqrt fp.Element
		Sqrt(&gSqrt, &x2)

		// gSqrt² must equal x²
		var check fp.Element
		check.Square(&gSqrt)
		assert.True(t, check.Equal(&x2), "Sqrt(x²)² must equal x² (i=%d)", i)
	}
}

// ---------------------------------------------------------------------------
// TestCompatSgn0
// Property test: Sgn0(x) == 1 iff x (in canonical form) ≤ (p-1)/2.
// The comparison is done using big.Int arithmetic.
// ---------------------------------------------------------------------------

var pMinus1Over2BigInt *big.Int

func init() {
	// p = 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab
	p, _ := new(big.Int).SetString(
		"4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787",
		10,
	)
	pMinus1Over2BigInt = new(big.Int).Rsh(new(big.Int).Sub(p, big.NewInt(1)), 1)
}

func TestCompatSgn0(t *testing.T) {
	for i := range 1000 {
		var x fp.Element
		_, err := x.SetRandom()
		require.NoError(t, err)

		// Canonical (non-Montgomery) representation as big.Int
		bits := x.Bits() // little-endian limbs, canonical form
		xBig := new(big.Int)
		for j := 5; j >= 0; j-- {
			xBig.Lsh(xBig, 64)
			xBig.Or(xBig, new(big.Int).SetUint64(bits[j]))
		}

		expectedSign := uint64(1) // 1 if x ≤ (p-1)/2
		if xBig.Cmp(pMinus1Over2BigInt) > 0 {
			expectedSign = 0
		}

		assert.Equal(t, expectedSign, Sgn0(&x), "Sgn0 mismatch at i=%d", i)
	}
}

// ---------------------------------------------------------------------------
// TestCompatSwuMapG1BE
// Known-answer + property test.
// Vectors were generated by running the current SwuMapG1BE implementation.
// Property: the output lies on the isogenous curve E' (y² == x³ + a·x + b).
// ---------------------------------------------------------------------------

var swuMapG1BEVectors = []struct{ uHex, xHex, yHex string }{
	{"065ff6427b0643bbd5de136d880db9a0cea91fda568cc5592e383453d770d6c975e3384aa5e74a2dfa17f29196cc128c", "0acc776da750b5095d0d8aab42ff4c77681d8738b5a86cd41837b671be16d3e0449e32684bca3170cfece28a05e1eb96", "0c6856cea1bc86340610f4ed95e3c845f19c03a748902472cf56d0af4dec2153e22e1a07fa11eb64787009a6017a6d50"},
	{"06f0d603b811e70310217be7917dc630cd5a6e7f7ffd6e76aca16152ee0054590a6a03f3089cd9958bb634fc3871a24a", "04fd00f11700da162b53cb61070da7b7eb5fdcf3abef8989da12c70568251678877d9bb4279c0ecbad529a669e67878d", "110f7bc6cc39c84757ac021cd6cb92a8cd59acc5f48ff759c7f13bb7b40eadd7cfbcae580e05cc9dd6eda371878aeee0"},
	{"0d5051d51146d2a7d730379cc156d4d1a687e9ec9401d65ff6c14cf3337419c398605accdc5979ba34b40ad7f9ab9229", "0d4fb0ec33958bed5b968c500065a662c6d7ea8f293f8d192ab59c24275392fa92a0da3d13fb5144667046668a55baea", "03e853037b5a8885889237c2b92e7169ef0fcc121e4d4412290112d2b5a414605de37a907d5d3329e80ac447f149cd9d"},
	{"04da65e7090cc541d6d917b9574901850758f25e8ec70f37172bf7d0b730ecaca7ca0902cbf10eeb6e0b16f5efc41a20", "0db07104cabc7d672b9730eb54cbffb5d73d94a02764a2ddcdb6e4c9ca0afbed8cabf640e02f0b900a931710806ba965", "0f4884ee64f61fd7cde720d603fef344a2e0276d2fc2bc2113bc79c7ec4240423d45aca459b817ed63b76b23ac39ead8"},
	{"0a5e748ae5d85cd7563e477894c2250248d797f050b3f9bde8d3ac2f55a19d481de6aabf0f688749d5ca478fecc7ecf9", "0de441585cdc30741bef0c5d37d8ada19474489602ff58e34136ce9cb87df4919986e18671a1f41af7e9c833cd1683fc", "00220991203ab05b933281fd1468ce0cee49f80202cb26d3a8938beef2f67604942edeb056afff914cea09d5c43b5a1d"},
	{"06e69f597f8274821a6fd2cec04c8f4cfdecda884e76f1963b5112c06c6b8774a37eda3b409fb752ad9645c293d579bc", "0bd4e508b27ce11f5039e4818f712a29ddeb0ecf6dd587a3443ad27a788c3ac7c346d78e250406d87b00dd81b20aaea8", "116f508aadae96815d1cc790802b05c4d6a152e2afc39ee16c05ba3bae96fd21830056e022d14a017027bd5a2c782834"},
	{"0d2be6c188e53ed32970645f4e1c0d3a2b5cb41cd077c856929d7ddb08f35772af65b25058172cee2cbb641019010a2d", "01a838b2bdff67ce0a25acd7b246ce53e08f2d418a3de6a170b9c6f333086e604702dd560173afcf7ec26f7998a55407", "0b188cc4796f8cfde3127c2e84de14d0664be6861d58c15c4c423cf48bb42910f8ecfeb523d9561ca0876db286d6e5dd"},
	{"11a2ccf0b7899073b838834ed8c5d223bc52d4e6dfbc87b900d68f7f4c3a8186ac801e4226d872c478bef39dad337cd0", "076605616e069d6bcabf48f8455194423edf658fca24fe1e1bcbf3f2252ef709b9108de039dc7f612bc3969c8b376563", "012710cd695cad2817812efe559099bcda6390f089481c804093c5878df72d319f9571e960b7dd6d51a7d59d197536ce"},
}

func mustDecodeHex48(t *testing.T, s string) [48]byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	require.NoError(t, err)
	require.Len(t, b, 48)
	var out [48]byte
	copy(out[:], b)

	return out
}

func mustFpFromHex(t *testing.T, s string) fp.Element {
	t.Helper()
	raw := mustDecodeHex48(t, s)
	var e fp.Element
	e.SetBytes(raw[:])

	return e
}

func TestCompatSwuMapG1BE(t *testing.T) {
	for idx, v := range swuMapG1BEVectors {
		u := mustFpFromHex(t, v.uHex)
		wantX := mustDecodeHex48(t, v.xHex)
		wantY := mustDecodeHex48(t, v.yHex)

		gotX, gotY := SwuMapG1BE(&u)
		assert.Equal(t, wantX, gotX.Bytes(), "X mismatch at vector %d", idx)
		assert.Equal(t, wantY, gotY.Bytes(), "Y mismatch at vector %d", idx)
	}

	// Property: random inputs produce points on E' (y² == x³ + a·x + b)
	for i := range 200 {
		var u fp.Element
		_, err := u.SetRandom()
		require.NoError(t, err)

		gX, gY := SwuMapG1BE(&u)

		// Verify y² == x³ + swuA·x + swuB
		var lhs, rhs, tmp fp.Element
		lhs.Square(gY) // y²
		rhs.Square(gX)
		rhs.Add(&rhs, &swuA)
		rhs.Mul(&rhs, gX)
		tmp.Set(&swuB)
		rhs.Add(&rhs, &tmp)
		assert.True(t, lhs.Equal(&rhs), "SwuMapG1BE output not on E' at i=%d", i)
	}
}

// ---------------------------------------------------------------------------
// TestCompatIsogenyMapG1
// Smoke test: gnark's G1Isogeny does not panic and produces a consistent
// result on valid E' points.  gnark IS the implementation — no oracle needed.
// ---------------------------------------------------------------------------

var isogenyMapG1SmokeVectors = []struct{ uHex, xHex, yHex string }{
	{"08fac73d5499381b6218f8a26acb705b5715447d9490c79832a04b5734faf2f59b14cc6c4c76336b110dea500eb989a6", "05db95201cfcc1b1670fdc158730523a4f5f269dbd0c83af6c10c6bbb4004ee5387ddd25c15bcc1011d728c883cce294", "1928754227e1b4386d7865795b13763529793175787338667154ec5e15ec2add9693a601bd2c987d5d2bbfa8c1f08a23"},
	{"082e3a50aeb5160697c38a88db433170e6535700073d97cb93ab01bf3e012c10534d98d4c5d721e9dc3a930e2bb80ded", "094dae268dd4f7517252f56537ed50f731a9977b4f9580306466afa8e79b59d14d330b5134c0f04b3646bf3687c68aac", "10691446df3e3427751be90c7232cf4c943e1084e6b39f352a4925f1029ddeb997eca8b5d4998e7d93498d6748dcad9e"},
	{"0cdfdab0c97105968793898681d710f8c13daaee0f17f7e5db88ae0cdb42eafa6d2ad39786dcdf0e9d599e9675bc8ab7", "00e86534a476dac7cb55167eb8c161029a1e8bf6fe73c96b0dde99a689e2e771116139466e81677aacae0486c9200cf6", "169b8b04eca6d391fd1d3292d812876aba14bb70063783192d1fc1290c6cb5199af28e85eb16a5172bc8c02a287bfad3"},
	{"165d36fd07187ec1400032446926c0934946f2585e58119e474e3428b1feba22f79a365e97e1515690afdfc72fecbd95", "0a1404eb9c26423e5d941a76df76cdead858627c26695fa86182e3d9d0439489a3d8867a2542e016a38fdac929e511e1", "069f4b0c3cc230f43264977ce61deb879b1246cfe5d2f2bbcfecbb1ad8a81e6d9d6e01f918f60130eb7c7b09eedd16dc"},
}

func TestCompatIsogenyMapG1(t *testing.T) {
	// Known-answer: apply gnark's isogeny to our SwuMapG1BE output and verify
	// the result matches pre-computed vectors.
	for idx, v := range isogenyMapG1SmokeVectors {
		u := mustFpFromHex(t, v.uHex)
		wantX := mustDecodeHex48(t, v.xHex)
		wantY := mustDecodeHex48(t, v.yHex)

		gX, gY := SwuMapG1BE(&u)
		isoX := *gX
		isoY := *gY
		hash_to_curve.G1Isogeny(&isoX, &isoY)

		assert.Equal(t, wantX, isoX.Bytes(), "Isogeny X mismatch at vector %d", idx)
		assert.Equal(t, wantY, isoY.Bytes(), "Isogeny Y mismatch at vector %d", idx)
	}
}

// ---------------------------------------------------------------------------
// TestCompatHash
// Known-answer test: Hash output matches pre-computed vectors.
// Vectors were generated by the current Hash implementation.
// ---------------------------------------------------------------------------

var hashVectors = []struct{ msg, domain, u0Hex, u1Hex string }{
	{"\x00test_hash_msg", "test_hash_domain", "06fbab49b24f7e632408368f75b0571bec3791c8c55503b26af1f843aaaabeffbcfd43bf77c83fe9daefb379600ca082", "171afedb2ea0bd0ba2608d3c39b0f94be133d7d644d01d501b7c945236ad712fa58be02916d344e75f437aae98f503fb"},
	{"\x01test_hash_msg", "test_hash_domain", "14c6581ce7724881c0a56b9eeddc34be8e696bcc1c34f9c313a011c762a3f53f5623dab53357f16ec83c595c199b36b6", "19bfbb4021d442232cbc4db58b19e4833371f4b0080d89e40443a9c23c1e3c6292e290b4b70ca20cd0c7c6306ba3fe61"},
	{"\x02test_hash_msg", "test_hash_domain", "0d2cbd74a6b58ea9deb25a09fd9a200dd606bac11dc684162cb9271d8878d85d4e8ff94024f74d9d1fe77050ea760e16", "0b51d6149e185fd3015555797deb007d28165c23782ff481f359556a1173e06b633744750080e213ac7a190931e9675e"},
	{"\x03test_hash_msg", "test_hash_domain", "1379b7ebcc5d418cdd93b2460b2652c5cc40ce971cbd942926bd78998341b586c8a41432d7693007b02bcccbd1dcbf7a", "01518d82c4d341a2353b1ed6c9db980e7d942114873f0ab3d7374142849fe42b7bb39b0866e19af2b69471c5fba5b05d"},
	{"\x04test_hash_msg", "test_hash_domain", "166e78868b0f89f4df78e5abc8c1c167de37b10f2857e3e629a6ffea75318c934aeb03665aed608d66a2206052dbcceb", "0893ca79f875429c3e552d022adaf32944b60bebea89c951a82c6dc8006087dcab17159b42a6c5d3dd0656950f92a80e"},
	{"\x05test_hash_msg", "test_hash_domain", "012916b602a1daa746946aabfdd33b67ef0efc6120207483c4aefead368a8de478bf41f4699ef495726fdcea5b940c66", "0b109e9e255a036b81330bb0e292811a9d7d9b899fed486b12a7fd4d9cb43636088f50cbbb196e2281ac1ef712a6d8f6"},
	{"\x06test_hash_msg", "test_hash_domain", "07f452ab51fd0f6d94f923c3c3062e4555212525ff075ef504a3bd775cff6c6bd8bbb104e0b4cacc347819396037a8fd", "0b357647045e4d076bd67b3049254b1bfef65e312d4c32b44e5b094ab5e0af5c1d7f407e58a05977b8aa4be5bf2fbefc"},
	{"\atest_hash_msg", "test_hash_domain", "0535dbfca8567e51f2bcebc5868114cdd53ba016cf7dbfb3075ac15f2bb7fa59bfb91514bdc6bc1cba802873c4e2692f", "125fcc2dfec5da9e51e639f81a78681b191b05795156f0a7f076058214dcbc5d3bb23aa7e9c213f149319a3492af8ca4"},
}

func TestCompatHash(t *testing.T) {
	for idx, v := range hashVectors {
		wantU0 := mustDecodeHex48(t, v.u0Hex)
		wantU1 := mustDecodeHex48(t, v.u1Hex)

		gU, err := Hash([]byte(v.msg), []byte(v.domain), 2, sha256.New)
		require.NoError(t, err)

		assert.Equal(t, wantU0, gU[0].Bytes(), "u0 mismatch at vector %d", idx)
		assert.Equal(t, wantU1, gU[1].Bytes(), "u1 mismatch at vector %d", idx)
	}
}

// ---------------------------------------------------------------------------
// TestCompatHashToG1GenericBESwu
// Known-answer + property test.
// Vectors were generated by the current HashToG1GenericBESwu implementation.
// Property: all outputs are valid BLS12-381 G1 points (on curve + in subgroup).
// ---------------------------------------------------------------------------

var hashToG1Vectors = []struct{ msg, domain, pointHex string }{
	{"\x00test_message_compat", "test_domain_compat", "0f1b515bcdf56b17354a57a65654d96b13e85963150e3a0e82befa1c0f534cc9a1c9eacb079a26944a1ac68046ad4f9a06021b3be13b29c2dadd9991958178df24886384e8b7cf6fee095bda3ff3f1277ecc1f1f3d75e9f05ce2d48a731c9498"},
	{"\x01test_message_compat", "test_domain_compat", "15fd546a343ad1bcad7744b92938f093f9b147fc68df48cd1d30dc83fc4384ed2ccb6be5c8638f1adf2a87f93c76b1c50efec8a48882d6a6f1227bec816aaaf3e248fa4bafdfbc35279a70ec0b806898fb4944286b86e1ca91c605a3ef828e65"},
	{"\x02test_message_compat", "test_domain_compat", "0d863b66cdb37246617faf00749e690c69241488d3d68bde10ed5ad7edf7973bf3546a9e6e6a772c4cc5fab0884e980816f9898387e818c3a8a4de68356aa1201f63fbcc7a15ec00bff86b9a46c9b693dfd3f6b249daef0450093b98c374c04d"},
	{"\x03test_message_compat", "test_domain_compat", "15422eb28e1e8181b3f5e835afd568ea158247013f71c39966972a9c77968fdf30bd9a10acd77d547295ec99af9e39810e48848502a79553c1b4c0e5ea98b2c0cd4a1fb7dea85508f741aaaa2272eb75e6cfb841dc61b2de965283202c721112"},
	{"\x04test_message_compat", "test_domain_compat", "0cd46a05b862ccd88319db39ffd1bd6e38c008488bf067d7db93e1b53557813def39b2694259c495a9f8f56fc79b316d14425f26dca82267163b3fc5da7ee1ea1e17cfec2bed69107bdc0e428882c72b41c950a53e07005e49943109e3bfdd9c"},
	{"\x05test_message_compat", "test_domain_compat", "10b3d47a246fe7e99f8cf12eb8eca29ae9ac257055dcf3ad18af0bdf8f9079630faf235ab2bface7b9ac05fd6c0f867118e83661d7be15ec5b341f7b4c775785a392125118c5eaed43895c507c378ce1ff01f808ea0986efad4f22926d2aa0a1"},
	{"\x06test_message_compat", "test_domain_compat", "1294f57a65af33b06d3ba7daf592e81e347f525a78aa81eb39a9eae99fc80d080bae0857ad7d8568c838cd1a27d3d61e0c8fe9ae1ffbf2de1a9ad74d0804ca723f7644d0cd33857b2a33dc25c889b20a68f25d9061e17323a51d896e0bfb53fc"},
	{"\atest_message_compat", "test_domain_compat", "0afbef0e9e9d9cc75a6cf2bf3dec0a0e79c91d20df2357cd91d975c680504d87dffee6f2d7643608ba8cd251ebaa7cbf12588250f3aa5e8ee4f3f16984f358042c2836f3b5de2723e3d35a4f85452545e9302749a21c001782c0d5d8bf2bf7e6"},
}

func TestCompatHashToG1GenericBESwu(t *testing.T) {
	// Known-answer check
	for idx, v := range hashToG1Vectors {
		wantRaw, err := hex.DecodeString(v.pointHex)
		require.NoError(t, err)

		gPoint, err := HashToG1GenericBESwu([]byte(v.msg), []byte(v.domain), sha256.New)
		require.NoError(t, err)

		gotRaw := gPoint.RawBytes()
		assert.Equal(t, wantRaw, gotRaw[:], "point mismatch at vector %d", idx)
	}

	// Property: random inputs produce valid BLS12-381 G1 points
	for i := range 50 {
		msg := []byte(string(rune(i)) + "prop_test_msg")
		domain := []byte("prop_test_domain")

		gPoint, err := HashToG1GenericBESwu(msg, domain, sha256.New)
		require.NoError(t, err)

		assert.True(t, gPoint.IsOnCurve(), "output not on curve at i=%d", i)
		assert.True(t, gPoint.IsInSubGroup(), "output not in subgroup at i=%d", i)
	}

	// Zero-value check: the point must not be the identity (infinity)
	gPoint, err := HashToG1GenericBESwu([]byte("non-empty"), []byte("domain"), sha256.New)
	require.NoError(t, err)
	var infinity bls12381.G1Affine
	assert.False(t, gPoint.Equal(&infinity), "hash-to-curve must not return the identity")
}
